version: 2

models:

  - name: stg_customer
    description: "Cleaned Customer Data"

    columns:
      - name: customer_id
        description: "Unique Customer Identifier"
        tests:
          - unique
          - not_null

      - name: first_name
        description: "Customer First Name"

      - name: last_name
        description: "Customer Last Name"

      - name: email
        description: "Customer Email Address"
        tests:
          - not_null

      - name: phone
        description: "Customer Phone Number"

      - name: city
        description: "Customer City"

      - name: state
        description: "Customer State"

      - name: country
        description: "Customer Country"

      - name: status
        description: "Customer Status"
        tests:
          - not_null