version: 2

models:

  - name: stg_customer
    description: "Cleaned Customer Data"

    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

      - name: email
        tests:
          - not_null

      - name: status
        tests:
          - not_null

  - name: dim_customer
    description: "Customer Dimension"

    columns:
      - name: customer_sk
        tests:
          - unique
          - not_null

      - name: status
        tests:
          - accepted_values:
              arguments:
                values:
                  - ACTIVE
                  - INACTIVE

  - name: dim_product
    description: "Product Dimension"

    columns:
      - name: product_sk
        tests:
          - unique
          - not_null

      - name: product_name
        tests:
          - not_null

  - name: fact_sales
    description: "Sales Fact Table"

    columns:
      - name: order_line_id
        tests:
          - unique
          - not_null

      - name: customer_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_customer')
                field: customer_sk

      - name: product_sk
        tests:
          - relationships:
              arguments:
                to: ref('dim_product')
                field: product_sk
