version: 2

sources:
  - name: bronze
    description: "Retail Data Warehouse Bronze Layer"

    database: "{{ env_var('DBT_DATABASE') }}"
    schema: "{{ env_var('DBT_SCHEMA') }}"
    tables:
      - name: CUSTOMER_RAW
        description: "Raw customer master data"

        freshness:
          warn_after:
            count: 30
            period: day

          error_after:
            count: 60
            period: day

        loaded_at_field: CREATED_DATE

      - name: PRODUCT_RAW
        description: "Raw product master data"

      - name: STORE_RAW
        description: "Raw store master data"

      - name: SUPPLIER_RAW
        description: "Raw supplier master data"

      - name: EMPLOYEE_RAW
        description: "Raw employee master data"

      - name: ORDER_HEADER_RAW
        description: "Raw order header data"

      - name: ORDER_LINE_RAW
        description: "Raw order line data"

      - name: PAYMENT_RAW
        description: "Raw payment transactions"

      - name: INVENTORY_RAW
        description: "Raw inventory data"

      - name: RETURNS_RAW
        description: "Raw returns data"